language: python
python:
  - '3.6'
sudo: false
script: python ./build.py --publish
after_success:
  - rm .gitignore
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
